# Generated by Django 6.0 on 2025-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=7)),
                ("phone_number", models.CharField(max_length=15)),
                ("Email", models.EmailField(max_length=254)),
                ("student_bio", models.TextField()),
                ("student_dob", models.DateField()),
                ("student_regestration", models.DateTimeField()),
                ("percentage", models.FloatField()),
            ],
        ),
    ]
